# Generated by Django 5.2.1 on 2025-05-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("una_id", models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlucoseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie_number", models.UUIDField()),
                ("device_timestamp", models.DateTimeField()),
                ("record_type", models.CharField(max_length=50)),
                (
                    "glucose_value_history_mg_dl",
                    models.FloatField(blank=True, null=True),
                ),
                ("glucose_scan_mg_dl", models.FloatField(blank=True, null=True)),
                (
                    "non_numeric_rapid_insulin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rapid_insulin_units", models.FloatField(blank=True, null=True)),
                (
                    "non_numeric_food_data",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("carbohydrates_grams", models.FloatField(blank=True, null=True)),
                ("carbohydrates_servings", models.FloatField(blank=True, null=True)),
                (
                    "non_numeric_basal_insulin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("basal_insulin_units", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("glucose_test_strip_mg_dl", models.FloatField(blank=True, null=True)),
                ("ketone_mmol_l", models.FloatField(blank=True, null=True)),
                ("mealtime_insulin_units", models.FloatField(blank=True, null=True)),
                ("correction_insulin_units", models.FloatField(blank=True, null=True)),
                (
                    "user_adjusted_insulin_units",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glucose_records",
                        to="level.user",
                    ),
                ),
            ],
        ),
    ]
