# Generated by Django 5.2.1 on 2025-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("level", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UnaUser",
        ),
    ]
